apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notely
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:iddchn/notely-kubernetes.git
    targetRevision: HEAD
    path: notely
  destination:
    server: https://kubernetes.default.svc
    namespace: notely/notely-chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true