apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.flask.serviceAccount.name }}
  namespace: {{ .Values.flask.metadata.namespace }}
  labels:
    environment: {{ .Values.flask.serviceAccount.environment }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.flask.serviceAccount.roleArn }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
