apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    {{- if .Values.storageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }}
  fsType: {{ .Values.storageClass.fsType }}
  encrypted: "{{ .Values.storageClass.encrypted }}"
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
