apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:idancohen55/argocd-demo-crm-apps.git
    targetRevision: HEAD
    path: infra-apps/external-charts/ingress-nginx
    helm:
      parameters:
        - name: controller.service.type
          value: LoadBalancer
        - name: controller.replicaCount
          value: "1"
        - name: controller.ingressClassResource.name
          value: nginx
        - name: controller.ingressClassResource.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true