global:
  storageClass: standard-rwo
labels:
  app: mongodb
architecture: replicaset

auth:
  enabled: true
  rootUser: root
  rootPassword: "123456"
  replicaSetKey: "myKey123456"

replicaCount: 3

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "375m"
    memory: "512Mi"
systemLogVerbosity: 3

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 500Mi

arbiter:
  enabled: false