apiVersion: v2
name: logging
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
dependencies:
  - name: elasticsearch
    version: 6.2.2
    repository: "file://./charts/elasticsearch"
  - name: fluent-bit
    version: 0.48.5
    repository: "file://./charts/fluent-bit"
  - name: kibana
    version: 8.5.1
    repository: "file://./charts/kibana"